openapi: 3.0.1
info:
  title: OpenAPI for NCATS Biomedical Translator Reasoners
  description: OpenAPI for NCATS Biomedical Translator Reasoners
  termsOfService: '{{url}}'
  contact:
    email: edeutsch@systemsbiology.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.9.2
externalDocs:
  description: Documentation for the NCATS Biomedical Translator Reasoners web services
  url: https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI
servers:
- url: /
tags:
- name: predicates
  description: Get supported relationships by source and target
  externalDocs:
    description: Documentation for the reasoner predicates function
    url: http://reasonerhost.ncats.io/overview.html#predicates
- name: query
  description: Query reasoner using a predefined question type
  externalDocs:
    description: Documentation for the reasoner query function
    url: http://reasonerhost.ncats.io/overview.html#query
paths:
  /predicates:
    get:
      tags:
      - predicates
      summary: Get supported relationships by source and target
      operationId: predicates_get
      responses:
        200:
          description: Predicates by source and target
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    type: array
                    description: Array of predicates
                    items:
                      type: string
                  description: Target map
                description: Source map
                example:
                  chemical_substance:
                    gene:
                    - directly_interacts_with
                    - decreases_activity_of
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.predicates_controller
  /query:
    post:
      tags:
      - query
      summary: Query reasoner via one of several inputs
      operationId: query
      requestBody:
        description: Query information to be submitted
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        400:
          description: Invalid status value
      x-swagger-router-controller: swagger_server.controllers.query_controller
      x-openapi-router-controller: swagger_server.controllers.query_controller
components:
  schemas:
    Query:
      required:
      - message
      type: object
      properties:
        message:
          $ref: '#/components/schemas/Message'
      additionalProperties: true
      x-body-name: request_body
    Message:
      type: object
      properties:
        results:
          type: array
          description: List of all returned potential answers for the query posed
          items:
            $ref: '#/components/schemas/Result'
        query_graph:
          $ref: '#/components/schemas/QueryGraph'
        knowledge_graph:
          type: object
          description: KnowledgeGraph object that contains all the nodes and edges
            referenced in any of the possible answers to the query OR connection information
            for a remote knowledge graph
          oneOf:
          - $ref: '#/components/schemas/KnowledgeGraph'
          - $ref: '#/components/schemas/RemoteKnowledgeGraph'
      additionalProperties: true
      example:
        knowledge_graph: ""
        results:
        - edge_bindings:
          - kg_id: ""
            qg_id: qg_id
          - kg_id: ""
            qg_id: qg_id
          node_bindings:
          - kg_id: ""
            qg_id: qg_id
          - kg_id: ""
            qg_id: qg_id
        - edge_bindings:
          - kg_id: ""
            qg_id: qg_id
          - kg_id: ""
            qg_id: qg_id
          node_bindings:
          - kg_id: ""
            qg_id: qg_id
          - kg_id: ""
            qg_id: qg_id
        query_graph:
          nodes:
          - curie: OMIM:603903
            id: n00
            type: disease
          - curie: OMIM:603903
            id: n00
            type: disease
          edges:
          - target_id: https://www.uniprot.org/uniprot/P00738
            id: e00
            source_id: https://omim.org/entry/603903
            type: affects
          - target_id: https://www.uniprot.org/uniprot/P00738
            id: e00
            source_id: https://omim.org/entry/603903
            type: affects
    Result:
      required:
      - edge_bindings
      - node_bindings
      type: object
      properties:
        node_bindings:
          type: array
          description: List of QNode-KNode bindings.
          items:
            $ref: '#/components/schemas/NodeBinding'
        edge_bindings:
          type: array
          description: List of QEdge-KEdge bindings.
          items:
            $ref: '#/components/schemas/EdgeBinding'
      description: One of potentially several results or answers for a query
      example:
        edge_bindings:
        - kg_id: ""
          qg_id: qg_id
        - kg_id: ""
          qg_id: qg_id
        node_bindings:
        - kg_id: ""
          qg_id: qg_id
        - kg_id: ""
          qg_id: qg_id
    NodeBinding:
      required:
      - kg_id
      - qg_id
      type: object
      properties:
        qg_id:
          type: string
          description: Query-graph node id, i.e. the `node_id` of a QNode
        kg_id:
          description: One or more knowledge-graph node ids, i.e. the `id` of a KNode
          oneOf:
          - type: string
          - type: array
            items:
              type: string
      example:
        kg_id: ""
        qg_id: qg_id
    EdgeBinding:
      required:
      - kg_id
      - qg_id
      type: object
      properties:
        qg_id:
          type: string
          description: Query-graph edge id, i.e. the `edge_id` of a QEdge
        kg_id:
          description: One or more knowledge-graph edge ids, i.e. the `id` of a KEdge
          oneOf:
          - type: string
          - type: array
            items:
              type: string
      example:
        kg_id: ""
        qg_id: qg_id
    KnowledgeGraph:
      required:
      - edges
      - nodes
      type: object
      properties:
        nodes:
          type: array
          description: List of nodes in the KnowledgeGraph
          items:
            $ref: '#/components/schemas/Node'
        edges:
          type: array
          description: List of edges in the KnowledgeGraph
          items:
            $ref: '#/components/schemas/Edge'
      additionalProperties: true
      description: A thought graph associated with this result. This will commonly
        be a linear path subgraph from one concept to another, but related items aside
        of the path may be included.
    RemoteKnowledgeGraph:
      required:
      - url
      type: object
      properties:
        url:
          type: string
          description: URL that provides programmatic access to the remote knowledge
            graph
          example: http://robokop.renci.org/api/kg
        credentials:
          type: array
          description: Credentials needed for programmatic access to the remote knowledge
            graph
          items:
            $ref: '#/components/schemas/Credentials'
        protocol:
          type: string
          default: neo4j
      description: A thought graph associated with this result that is not repeated
        here, but stored elsewhere in a way that can be remotely accessed by the reader
        of this Message
    Credentials:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
          description: Username needed for programmatic access to the remote knowledge
            graph
        password:
          type: string
          description: Password needed for programmatic access to the remote knowledge
            graph
      additionalProperties: true
      description: Credentials needed for programmatic access to the remote knowledge
        graph
    QueryGraph:
      required:
      - edges
      - nodes
      type: object
      properties:
        nodes:
          type: array
          description: List of nodes in the QueryGraph
          items:
            $ref: '#/components/schemas/QNode'
        edges:
          type: array
          description: List of edges in the QueryGraph
          items:
            $ref: '#/components/schemas/QEdge'
      additionalProperties: true
      description: A graph intended to be the thought path to be followed by a reasoner
        to answer the question. This graph is a representation of a question.
      example:
        nodes:
        - curie: OMIM:603903
          id: n00
          type: disease
        - curie: OMIM:603903
          id: n00
          type: disease
        edges:
        - target_id: https://www.uniprot.org/uniprot/P00738
          id: e00
          source_id: https://omim.org/entry/603903
          type: affects
        - target_id: https://www.uniprot.org/uniprot/P00738
          id: e00
          source_id: https://omim.org/entry/603903
          type: affects
    QNode:
      required:
      - id
      type: object
      properties:
        id:
          type: string
          description: 'QueryGraph internal identifier for this QNode. Recommended
            form: n00, n01, n02, etc.'
          example: n00
        curie:
          type: string
          description: CURIE identifier for this node
          example: OMIM:603903
        type:
          $ref: '#/components/schemas/BiolinkEntity'
      additionalProperties: true
      description: A node in the QueryGraph
      example:
        curie: OMIM:603903
        id: n00
        type: disease
    QEdge:
      required:
      - id
      - source_id
      - target_id
      type: object
      properties:
        id:
          type: string
          description: 'QueryGraph internal identifier for this QEdge. Recommended
            form: e00, e01, e02, etc.'
          example: e00
        type:
          $ref: '#/components/schemas/BiolinkRelation'
        source_id:
          type: string
          description: Corresponds to the @id of source node of this edge
          example: https://omim.org/entry/603903
        target_id:
          type: string
          description: Corresponds to the @id of target node of this edge
          example: https://www.uniprot.org/uniprot/P00738
      additionalProperties: true
      description: An edge in the QueryGraph
      example:
        target_id: https://www.uniprot.org/uniprot/P00738
        id: e00
        source_id: https://omim.org/entry/603903
        type: affects
    Node:
      required:
      - id
      type: object
      properties:
        id:
          type: string
          description: CURIE identifier for this node
          example: OMIM:603903
        name:
          type: string
          description: Formal name of the entity
          example: Haptoglobin
        type:
          type: array
          items:
            $ref: '#/components/schemas/BiolinkEntity'
      additionalProperties: true
      description: A node in the thought subgraph
    Edge:
      required:
      - id
      - source_id
      - target_id
      type: object
      properties:
        id:
          type: string
          description: Local identifier for this node which is unique within this
            KnowledgeGraph, and perhaps within the source reasoner's knowledge graph
          example: "553903"
        type:
          $ref: '#/components/schemas/BiolinkRelation'
        source_id:
          type: string
          description: Corresponds to the @id of source node of this edge
          example: https://omim.org/entry/603903
        target_id:
          type: string
          description: Corresponds to the @id of target node of this edge
          example: https://www.uniprot.org/uniprot/P00738
      additionalProperties: true
      description: An edge in the thought subgraph linking two nodes
    BiolinkEntity:
      type: string
      description: A subclass of named_thing (snake_case)
      example: disease
      externalDocs:
        description: Biolink model entities
        url: https://biolink.github.io/biolink-model/docs/NamedThing.html
    BiolinkRelation:
      type: string
      description: A relation, i.e. child of related_to (snake_case)
      example: affects
      externalDocs:
        description: Biolink model relations
        url: https://biolink.github.io/biolink-model/docs/related_to.html

